version: build{build}

branches:
  except:
    - develop/travis

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set GOPATH=c:\gopath
  - set QTDIR=C:\Qt\5.13.2\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;%GOPATH%\bin;
  - go get qpm.io/qpm
  - go install qpm.io/qpm
  - dir %GOPATH%\bin
  - cd tests/asyncfutureunittests
  - qpm install
  - qmake asyncfutureunittests.pro
  - nmake
  - dir /w
  - dir release /w
  - release\asyncfutureunittests
  - cd ..\compilererrors
  - qmake
  - nmake & exit 0
